language: python
python:
  - "2.6"
  - "2.7"
addons:
  sauce_connect:
    username: "henrikhodne"
    access_key:
      secure: "DROnN91K1QZPCw35H63mISddzGfD3Lm4c4m1p3ZHtbqSuqONQYYMIX/4vu0e\ngP+SYdz1MkA5Lkf3DYMqf/ZjPjq3iWlh3rYgyuQMYE5RB9Nuy6jpPHg1SXW5\nfs1OHl2aSGYNtO/upPqSHu1TJ43qXMxhQJ1OeymfJKS16HvCQNM="

install:
  - pip install selenium nose --use-mirrors

before_script:
  - curl https://gist.github.com/santiycr/5139581/raw/python_appengine_setup.py | python

script:
  - python cssify.py -t
  - nosetests --processes=5 --process-timeout=600 -v tests
